# Generated by Django 3.2 on 2021-05-01 16:22

import Gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True, verbose_name='عنوان تصویر')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='توضیح خیلی کوتاه')),
                ('image', models.ImageField(null=True, upload_to=Gallery.models.get_image_path)),
            ],
        ),
    ]
