# Generated by Django 3.2 on 2021-05-01 16:37

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gallery',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='active',
            field=models.BooleanField(default=False, verbose_name='نمایش داده شود / نشود'),
        ),
    ]
