# Generated by Django 3.2 on 2021-05-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_auto_20210501_2107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='GalleryModel',
        ),
    ]
