# Generated by Django 3.2 on 2021-05-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0003_rename_gallery_gallerymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerymodel',
            options={'verbose_name': 'گالری', 'verbose_name_plural': 'تصاویر'},
        ),
    ]
