# Generated by Django 3.2 on 2021-05-01 18:18

import Blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True, verbose_name='عنوان دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True, verbose_name='عنوان تگ')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='عنوان بلاگ')),
                ('image', models.ImageField(null=True, upload_to=Blog.models.get_image_path, verbose_name='تصویر بلاگ')),
                ('image2', models.ImageField(blank=True, null=True, upload_to=Blog.models.get_image_path, verbose_name='تصویر بلاگ2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to=Blog.models.get_image_path, verbose_name='تصویر بلاگ3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to=Blog.models.get_image_path, verbose_name='تصویر بلاگ4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to=Blog.models.get_image_path, verbose_name='تصویر بلاگ5')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ نوشتن خبر')),
                ('description', models.TextField(null=True, verbose_name='توضیحات')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ManyToManyField(null=True, to='Blog.Category', verbose_name='دسته بندی')),
                ('tags', models.ManyToManyField(null=True, to='Blog.Tag', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ ها',
            },
        ),
    ]
