# Generated by Django 3.2 on 2021-05-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_comments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='منتشر شود / نشود'),
        ),
    ]
