# Generated by Django 3.2 on 2021-06-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_comments_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date'], 'verbose_name': 'بلاگ', 'verbose_name_plural': 'بلاگ ها'},
        ),
    ]
