# Generated by Django 3.2 on 2021-06-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0002_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'اطلاعات', 'verbose_name_plural': 'اطلاعات'},
        ),
    ]
