# Generated by Django 3.2 on 2021-05-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_blog_description2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True, verbose_name='نام نظر دهنده')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='شماره نظر دهنده')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='ایمیل نظر دهنده')),
                ('comment', models.TextField(null=True, verbose_name='نظر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
    ]
