# Generated by Django 3.2 on 2021-05-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='شماره تلفن')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(null=True, verbose_name='ادرس')),
            ],
            options={
                'verbose_name': 'ادرس',
                'verbose_name_plural': 'ادرس ها',
            },
        ),
    ]
